from __future__ import annotations

from dataclasses import dataclass
import numpy as np
from scipy.linalg import solve

from .jacobian import finite_difference_jacobian
from .nonlinear_solver import NewtonReport


@dataclass
class NewtonSolverWithJacobian:
    """Newton-Raphson solver that accepts an analytic/AD Jacobian callback.

    The previous framework versions built dense finite-difference Jacobians
    inside the Newton loop. Step 4C keeps that option as a fallback, but the
    preferred path is to pass a Jacobian callback generated by automatic
    differentiation. The interface is intentionally compact:

        solve(func, jac, x0, lower, upper)

    where ``func(x)`` returns the residual and ``jac(x)`` returns dR/dx.
    """

    tol: float = 1.0e-8
    max_iter: int = 14
    verbose: bool = False
    min_damping: float = 1.0e-4
    acceptable_tol: float | None = None
    acceptable_min_iterations: int = 1
    fd_rel_eps: float = 1.0e-7
    regularization: float = 0.0

    def solve(self, func, x0: np.ndarray, jac=None, lower=None, upper=None) -> tuple[np.ndarray, NewtonReport]:
        x = np.asarray(x0, dtype=float).copy()
        lower_arr = None if lower is None else np.asarray(lower, dtype=float)
        upper_arr = None if upper is None else np.asarray(upper, dtype=float)

        f = np.asarray(func(x), dtype=float)
        norm0 = float(np.linalg.norm(f, ord=2))
        if self.verbose:
            print(f"    Newton initial residual: {norm0:.6e}")
        if norm0 < self.tol:
            return x, NewtonReport(True, 0, norm0, 1.0)

        last_damping = 1.0
        for iteration in range(1, self.max_iter + 1):
            if jac is None:
                mat = finite_difference_jacobian(func, x, f0=f, rel_eps=self.fd_rel_eps)
            else:
                mat = np.asarray(jac(x), dtype=float)

            if self.regularization > 0.0:
                mat = mat + self.regularization * np.eye(mat.shape[0])

            try:
                dx = solve(mat, -f, assume_a="gen")
            except Exception as exc:  # pragma: no cover - rare fallback path
                if jac is not None:
                    # In difficult switching cases the AD matrix can become
                    # nearly singular. Rebuild once with a numerical Jacobian
                    # rather than failing the whole timestep immediately.
                    mat = finite_difference_jacobian(func, x, f0=f, rel_eps=self.fd_rel_eps)
                    dx = solve(mat, -f, assume_a="gen")
                else:
                    raise RuntimeError(f"Linear solve failed during Newton iteration {iteration}: {exc}") from exc

            damping = 1.0
            accepted = False
            current_norm = float(np.linalg.norm(f, ord=2))
            candidate = x.copy()
            f_candidate = f.copy()

            while damping >= self.min_damping:
                candidate = x + damping * dx
                if lower_arr is not None:
                    candidate = np.maximum(candidate, lower_arr)
                if upper_arr is not None:
                    candidate = np.minimum(candidate, upper_arr)

                f_candidate = np.asarray(func(candidate), dtype=float)
                candidate_norm = float(np.linalg.norm(f_candidate, ord=2))

                if candidate_norm < current_norm or candidate_norm < self.tol:
                    x = candidate
                    f = f_candidate
                    last_damping = damping
                    accepted = True
                    break
                damping *= 0.5

            if not accepted:
                x = candidate
                f = f_candidate
                last_damping = damping

            norm = float(np.linalg.norm(f, ord=2))
            if self.verbose:
                print(f"    Newton {iteration:02d}: residual={norm:.6e}, damping={last_damping:.3e}")
            if norm < self.tol:
                return x, NewtonReport(True, iteration, norm, last_damping)
            if (
                self.acceptable_tol is not None
                and iteration >= self.acceptable_min_iterations
                and norm < self.acceptable_tol
            ):
                return x, NewtonReport(True, iteration, norm, last_damping)

        return x, NewtonReport(False, self.max_iter, float(np.linalg.norm(f, ord=2)), last_damping)
