"""Example 06: Step 4C conservative live-oil black-oil model with AD Jacobian.

This example upgrades the phase-switching prototype from Step 4B. In
undersaturated cells the third primary variable is Rs; in saturated cells it is
Sg. Unlike Step 4B, the gas-component conservation equation is active in both
cell types. The Newton Jacobian is generated by JAX automatic differentiation
when JAX is available; otherwise the framework falls back to a dense numerical
Jacobian.
"""

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from blackoil import (
    CartesianGrid1D,
    Rock,
    BlackOilPVTTable,
    TabulatedFluid,
    CoreyThreePhaseRelPerm,
    StateBlackOil,
    BHPWell,
    ConservativeLiveOilPhaseSwitchingSimulator,
    NewtonSolverWithJacobian,
    day,
    md_to_m2,
    bar,
)
from blackoil.io import ensure_dir


def reports_to_frame(reports) -> pd.DataFrame:
    rows = []
    for r in reports:
        rows.append(
            {
                "time_days": r.time / day,
                "dt_days": r.dt / day,
                "newton_iterations": r.newton.iterations,
                "residual_norm": r.newton.residual_norm,
                "p_min_bar": r.min_pressure / bar,
                "p_max_bar": r.max_pressure / bar,
                "sw_min": r.min_sw,
                "sw_max": r.max_sw,
                "sg_min": r.min_sg,
                "sg_max": r.max_sg,
                "so_min": r.min_so,
                "so_max": r.max_so,
                "rs_min_sm3_sm3": r.min_rs,
                "rs_max_sm3_sm3": r.max_rs,
                "saturated_cells": r.saturated_cells,
                "undersaturated_cells": r.undersaturated_cells,
                "switched_to_saturated": r.switched_to_saturated,
                "switched_to_undersaturated": r.switched_to_undersaturated,
                "oil_rate_m3_day": r.oil_rate * day,
                "water_prod_rate_m3_day": r.water_rate * day,
                "free_gas_rate_sm3_day": r.free_gas_rate * day,
                "gas_component_rate_sm3_day": r.gas_component_rate * day,
                "producing_gor_sm3_sm3": r.producing_gor,
                "recovery_factor": r.recovery_factor,
                "oil_mb_error_relative": r.oil_material_balance_error_relative,
                "water_mb_error_relative": r.water_material_balance_error_relative,
                "gas_mb_error_relative": r.gas_material_balance_error_relative,
            }
        )
    return pd.DataFrame(rows)


def main() -> None:
    out = ensure_dir(ROOT / "outputs" / "example_06_live_oil_conservative_ad")

    grid = CartesianGrid1D(nx=6, length=300.0, area=1600.0)
    p0 = 280.0 * bar

    rock = Rock(
        porosity_ref=0.23,
        permeability=md_to_m2(135.0),
        compressibility=4.0e-10,
        p_ref=p0,
    )

    table = BlackOilPVTTable.from_csv(ROOT / "data" / "pvt" / "live_oil_pvt.csv")
    water = TabulatedFluid(
        name="water",
        table=table,
        b_key="Bw",
        mu_key="muw_pa_s",
        rho_ref=1000.0,
        density_key="rhow_kg_m3",
    )
    oil = TabulatedFluid(
        name="live_oil",
        table=table,
        b_key="Bo",
        mu_key="muo_pa_s",
        rho_ref=780.0,
        density_key="rhoo_kg_m3",
        rs_key="Rs_sm3_sm3",
    )
    gas = TabulatedFluid(
        name="gas",
        table=table,
        b_key="Bg",
        mu_key="mug_pa_s",
        rho_ref=1.2,
        density_key="rhog_kg_m3",
    )

    relperm = CoreyThreePhaseRelPerm(
        swc=0.18,
        sor=0.20,
        sgc=0.02,
        krw0=0.32,
        kro0=0.86,
        krg0=0.72,
        nw=2.4,
        no=2.1,
        ng=2.0,
    )

    initial_rs = 155.0
    initial_pbub = float(oil.bubble_point_pressure(initial_rs))
    wells = [BHPWell(name="PROD_BHP", cell=grid.nx - 1, bhp=105.0 * bar, well_index=1.0e-14)]
    # Step 4C supports a mixed phase map. The left part starts undersaturated
    # and uses Rs as the third primary variable. The last two cells start
    # saturated and use Sg as the third primary variable. This exercises the
    # conservative primary-variable switching machinery directly.
    is_saturated = np.zeros(grid.nx, dtype=bool)
    is_saturated[-2:] = True
    x_primary = np.full(grid.nx, initial_rs, dtype=float)
    x_primary[is_saturated] = 0.025
    state = StateBlackOil(
        p=np.full(grid.nx, p0, dtype=float),
        sw=np.full(grid.nx, relperm.swc + 0.025, dtype=float),
        x=x_primary,
        is_saturated=is_saturated,
    )

    solver = NewtonSolverWithJacobian(
        tol=1.0e-7,
        max_iter=18,
        verbose=False,
        acceptable_tol=2.0e-3,
        acceptable_min_iterations=2,
        regularization=0.0,
    )
    sim = ConservativeLiveOilPhaseSwitchingSimulator(
        grid,
        rock,
        water,
        oil,
        gas,
        relperm,
        state,
        wells=wells,
        solver=solver,
        jacobian_mode="jax",
        sg_switch_tol=2.0e-5,
    )

    results = sim.run_adaptive(
        t_final=8.0 * day,
        dt_initial=1.0 * day,
        dt_min=0.01 * day,
        dt_max=2.0 * day,
        max_ds=0.080,
    )

    df = reports_to_frame(results["reports"])
    df.to_csv(out / "conservative_ad_timestep_report.csv", index=False)
    np.savez(
        out / "conservative_ad_results.npz",
        time=results["time"],
        pressure=results["pressure"],
        sw=results["sw"],
        sg=results["sg"],
        so=results["so"],
        rs=results["rs"],
        is_saturated=results["is_saturated"],
    )

    x = grid.centers
    time_days = results["time"] / day
    pressure_bar = results["pressure"] / bar
    sg = results["sg"]
    rs = results["rs"]
    sat_fraction = np.mean(results["is_saturated"], axis=1)
    sample_ids = np.unique(np.array([0, len(time_days) // 3, 2 * len(time_days) // 3, -1]))

    plt.figure(figsize=(7.8, 4.8))
    for idx in sample_ids:
        plt.plot(x, pressure_bar[idx], label=f"t = {time_days[idx]:.0f} d")
    plt.axhline(initial_pbub / bar, linestyle="--", linewidth=1.1, label=f"initial bubble point ≈ {initial_pbub / bar:.0f} bar")
    plt.xlabel("x [m]")
    plt.ylabel("Oil pressure [bar]")
    plt.title("Step 4C conservative AD black-oil: pressure")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out / "pressure_profiles.png", dpi=180)

    plt.figure(figsize=(7.8, 4.8))
    for idx in sample_ids:
        plt.plot(x, sg[idx], label=f"t = {time_days[idx]:.0f} d")
    plt.xlabel("x [m]")
    plt.ylabel("Free-gas saturation")
    plt.title("Free gas in saturated cells under conservative switching")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out / "gas_saturation_profiles.png", dpi=180)

    plt.figure(figsize=(7.8, 4.8))
    for idx in sample_ids:
        plt.plot(x, rs[idx], label=f"t = {time_days[idx]:.0f} d")
    plt.xlabel("x [m]")
    plt.ylabel("Rs [sm³/sm³]")
    plt.title("Rs solved conservatively in undersaturated cells")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out / "solution_gas_ratio_profiles.png", dpi=180)

    plt.figure(figsize=(7.8, 4.8))
    plt.plot(time_days, sat_fraction, marker="o")
    plt.xlabel("Time [days]")
    plt.ylabel("Fraction of saturated cells")
    plt.title("Phase-state evolution")
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(out / "saturated_fraction.png", dpi=180)

    plt.figure(figsize=(7.8, 4.8))
    plt.plot(df["time_days"], df["oil_rate_m3_day"], marker="o", label="Oil")
    plt.plot(df["time_days"], df["water_prod_rate_m3_day"], marker="s", label="Water")
    plt.xlabel("Time [days]")
    plt.ylabel("Production rate [m³/day]")
    plt.title("Liquid production rates")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out / "liquid_well_rates.png", dpi=180)

    plt.figure(figsize=(7.8, 4.8))
    plt.plot(df["time_days"], df["free_gas_rate_sm3_day"], marker="o", label="Free gas")
    plt.plot(df["time_days"], df["gas_component_rate_sm3_day"], marker="s", label="Gas component")
    plt.xlabel("Time [days]")
    plt.ylabel("Gas rate [sm³/day]")
    plt.title("Gas production")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out / "gas_well_rates.png", dpi=180)

    plt.figure(figsize=(7.8, 4.8))
    plt.semilogy(df["time_days"], np.abs(df["oil_mb_error_relative"]) + 1.0e-30, label="Oil")
    plt.semilogy(df["time_days"], np.abs(df["water_mb_error_relative"]) + 1.0e-30, label="Water")
    plt.semilogy(df["time_days"], np.abs(df["gas_mb_error_relative"]) + 1.0e-30, label="Gas")
    plt.xlabel("Time [days]")
    plt.ylabel("Absolute relative material-balance error")
    plt.title("Material-balance diagnostics")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out / "material_balance_error.png", dpi=180)

    print(f"Example 06 finished. Results written to: {out}")
    print(f"Initial undersaturated Rs = {initial_rs:.1f} sm3/sm3; bubble point = {initial_pbub / bar:.1f} bar")
    print(df.tail(1).to_string(index=False))


if __name__ == "__main__":
    main()
